name = "thumb-zone-nav"
type = "theme"
uid = "24fcd9b2-c780-8410-17af-2ff686eae2d2dcbc3bec"


[build]
# This tells Shopify CLI to watch for changes
watch = [
  "blocks/*.liquid",
  "assets/*.js",
  "assets/*.css",
  "snippets/*.liquid"
]

api_version = "2025-01"